### ISSUE TITLE
Improve current tracker evaluation routine

### ISSUE THREAD

**Issue by jinified** [jinified/selam#5]
## Description
- [x] use rotated bounding box to label ground truth
- [ ] determine output of a tracker in order use available measurement tool
- [x] use model-free tracker to generate ground truth 

## Recommended annotators
1. [aibu, VOTChallenge image annotator](https://github.com/votchallenge/aibu)
2. [Fast Image Annotation Tool](https://github.com/christopher5106/FastAnnotationTool)
3. [LabelMe MIT](http://labelme.csail.mit.edu/Release3.0/)

## Benchmarks
1. [VOT Challenge](http://www.votchallenge.net/)
2. [MOT Challenge](https://motchallenge.net/)

**Comment by jinified** [comment]
Decided to used aibu which supports rotated bounding box and VOT as final evaluation tool
