### ISSUE TITLE
Improve object tracking routine

### ISSUE THREAD

**Issue by jinified** [jinified/selam#7]
## Description
To improve accuracy and robustness of tracking algorithms:
- [ ] include online update mechanism
- [ ] add prior information as part of tracking criteria
- [ ] compare and contrast different state-of-the-art tracking schemes
